### ISSUE TITLE
[Design] Create the wireframes for the application.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#1]
Wireframes should cover the below scenarios.
- Examiner sign-in page - This should have the biometric sign-in.
- Exam schedule page - Examiners should able to view the exam schedules for that day and the exam schedule should be sorted by time.
- Exam page - After clicking the one of schedule examiner will be directed to this page and this page should contain the start verifying student button.
- Student verification page - This page will verify the students via biometrics and there should be custom authentication for the examiner if the biometrics can't be used to identify the student(eg: Let's say we have the fingerprint to verify the student but the finger of the student was injured.)
- Live report page - Examiners will be able to view the summary of the exam attendance like percentage presented, how many and etc.

**Comment by Malith-19** [comment]
@sanduninduwara Let's put the wireframe design here for further reference once you guys finalize it.

**Comment by sanduninduwara** [comment]
https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=0%3A1&mode=design&t=iQUlSYpAO1E7ueXP-1

**Comment by Malith-19** [comment]
Added few comments.
@sanduninduwara @Wenuka19 @chamodmadhusanka @yasirulakshan @KesaviAravinthan @laksi1999 @Tharsha-Sivapalarajah

**Comment by chamodmadhusanka** [comment]
> Added few comments. @sanduninduwara @Wenuka19 @chamodmadhusanka @yasirulakshan @KesaviAravinthan @laksi1999 @Tharsha-Sivapalarajah

Fixed improvements in `Attendance Marking` pages. Relates [this](https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=0%3A1&mode=design&t=iQUlSYpAO1E7ueXP-1)
