### ISSUE TITLE
[Impl] Implement attendance marking page for students.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#11]
Create the student attendance marking page.

You can use the fingerprint component https://github.com/cse-mosip/Exam-Attendance-UI/issues/5 and the custom sign in component for the student https://github.com/cse-mosip/Exam-Attendance-UI/issues/8

Refer the **attendance collecting page**  and **student sign in via index page** in [Figma design](https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=0%3A1&mode=design&t=iQUlSYpAO1E7ueXP-1)

**Comment by niruthikka24** [comment]
[https://github.com/cse-mosip/Exam-Attendance-UI/pull/32](url)
