### ISSUE TITLE
[Impl] Improve the UI in the fingerprint scanner component.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#24]
Let's strict the UI design and implement that like below.

![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/79596630/3c43d7cf-cc2e-47f9-b1b5-6e1bb575bf65)

- [x] Use the color theme in the design.
- [x] don't have to do the component alignment since this is a component.(remove the `<div>`
- [x] Add box-shadow
- [ ] Add the box color to the design.
- [x] For the fingerprint let's use the fingerprint image instead of an icon.
- [ ] update `use index` text to `use password`
- [ ] Add prop to pass a function to on-lick in `use the password`. Then we can pass the function to the component and use it flexibly for both students and examiners.

**Comment by springyboiii** [comment]
[https://github.com/cse-mosip/Exam-Attendance-UI/pull/28](url)
