### ISSUE TITLE
[Design] Add the theme colors to the wireframes.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#3]
After receiving the theme color palate let's add them into wireframes and finalize the UI design.

**Comment by sanduninduwara** [comment]
let's recreate the same wireframes using MUI components 
here is an example login page 
https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=38-4270&mode=design&t=hizhHS6H7RvJQU5T-0

**Comment by Wenuka19** [comment]
@yasirulakshan @KesaviAravinthan @chamodmadhusanka @laksi1999 @Tharsha-Sivapalarajah Can you implement the rest? We have designed some
Created the `Attendance Monitoring` and `Login Successful` pages

**Comment by Wenuka19** [comment]
All the wireframes are recreated. Please check

**Comment by laksi1999** [comment]
Recreated the `Student signin page via index` and  `Schedule  Page`

**Comment by KesaviAravinthan** [comment]
Updated design of `Examiner Login Page` UI

**Comment by chamodmadhusanka** [comment]
Created Fingerprint login pages for Examiner and attendance marking

**Comment by yasirulakshan** [comment]
Added some refinements on UI pages

**Comment by Tharsha-Sivapalarajah** [comment]
Updated the Design of UI Pages by Adding some Refinements. 
Eg - Examiner --> Supervisor
