### ISSUE TITLE
[Impl] Implement the fingerprint scanner component.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#5]
Implement the fingerprint scanner component.

![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/79596630/8001d09c-2ff2-47a6-a8bf-c1b4743df15e)

Refer the **examiner login page** in  [figma design](https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=0%3A1&mode=design&t=iQUlSYpAO1E7ueXP-1)

**Comment by springyboiii** [comment]
Starting

**Comment by springyboiii** [comment]
PR: [https://github.com/cse-mosip/Exam-Attendance-UI/pull/14](url)
