### ISSUE TITLE
Replace terminology "Examiner" to "Supervisor"

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [cse-mosip/Exam-Attendance-UI#50]
It is better to change the terminology from "Examiner" to "Supervisor" in every place since that is the terminology used currently.

**Comment by Tharsha-Sivapalarajah** [comment]
[Replaced Terminology from Examiner to Supervisor](https://github.com/cse-mosip/Exam-Attendance-UI/pull/52)
