### ISSUE TITLE
[Impl] Displaying Proper Timestamp in Exam Attendance Report Monitoring Page

### ISSUE THREAD

**Issue by Tharsha-Sivapalarajah** [cse-mosip/Exam-Attendance-UI#51]
It is better to include the exact time other than the date in the Timestamp shown in the Exam Attendance Monitoring Page regarding the Attendance and Paper Collected as per the UI design.

![Attendance Monitoring Page](https://github.com/cse-mosip/Exam-Attendance-UI/assets/104376854/ec53db24-b111-4f80-879f-f5d498038ece)

![UI Design](https://github.com/cse-mosip/Exam-Attendance-UI/assets/104376854/55be356e-66ba-450b-9543-876abc267277)

**Comment by Malith-19** [comment]
mmm yeah, Also I think we don't need to show the date in every row right? @sanduninduwara

**Comment by Malith-19** [comment]
And also it's better if we can align the back button with the heading right? Please include the navbar top of the page.

**Comment by sanduninduwara** [comment]
updated the design
![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/80301407/fa2159cb-1d1b-479b-8766-2559174c4ecd)

**Comment by Jithmi004** [comment]
> It is better to include the exact time other than the date in the Timestamp shown in the Exam Attendance Monitoring Page regarding the Attendance and Paper Collected as per the UI design.
> 
> ![Attendance Monitoring Page](https://github.com/cse-mosip/Exam-Attendance-UI/assets/104376854/ec53db24-b111-4f80-879f-f5d498038ece)
> 
> ![UI Design](https://github.com/cse-mosip/Exam-Attendance-UI/assets/104376854/55be356e-66ba-450b-9543-876abc267277)
> 

@Tharsha-Sivapalarajah The timestamp in the current design is just hardcoded data and will be replaced with the proper timestamp

**Comment by Malith-19** [comment]
@Jithmi004 @chathuranga-jayanath-99 
Can we revamp the UI implementation since there are some changes in the design like 
1. show to date close to the percentage.

**Comment by Jithmi004** [comment]
@Malith-19 ack

**Comment by chathuranga-jayanath-99** [comment]
@sanduninduwara 

> updated the design ![image](https://user-images.githubusercontent.com/80301407/254181688-fa2159cb-1d1b-479b-8766-2559174c4ecd.png)

Don't we need to display the module name and module code?

**Comment by chathuranga-jayanath-99** [comment]
- [x] add date separately on top
- [x] add time for `attendance` and `paper collected`
- [x] add rows per page option
- [x] Align back button with the attendance monitor heading
- [x] add the navbar

**Comment by Jithmi004** [comment]
https://github.com/cse-mosip/Exam-Attendance-UI/pull/54 Please check the changes
