### ISSUE TITLE
[Integrate] Use the exams API to retrive the exam schedule.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#59]
Please refer the `admin/exam/all-exams` API in the [swagger file](https://github.com/cse-mosip/Attendance-Service/blob/main/APIDocumentation.yml).

This call should happen on the `Exam schedule` page. If the API call takes too much time(more than 2/3 secs) add a loader component to the page too.

**Comment by thilinawaks1999** [comment]
This is completed. But there is an error in Api. Backend team working on that. After they fixed it need to check from my side. Will raise a PR after that.
