### ISSUE TITLE
[Impl] Implement the custom login form component.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#6]
implement the custom sign-in page for the examiner when they have to use custom login instead of the biometric login.

![image](https://github.com/cse-mosip/Exam-Attendance-UI/assets/79596630/f9c8ec79-2e2a-4669-91a3-dd5b53fdd719)

refer the **examiner login page** in [figma design](https://www.figma.com/file/ewqkiF5GG353Ae8aP2f3df/Scheduled-Page?type=design&node-id=0%3A1&mode=design&t=iQUlSYpAO1E7ueXP-1)

**Comment by thilinawaks1999** [comment]
Implement the custom login form component => In progress
