### ISSUE TITLE
[Integrate] Use exam API to retrieve data to show in the attendance monitoring page.

### ISSUE THREAD

**Issue by Malith-19** [cse-mosip/Exam-Attendance-UI#60]
Refer to the `admin/exam/get-exam/{examId}` under the EXAMS in the[ backend swagger](https://github.com/cse-mosip/Attendance-Service/blob/main/APIDocumentation.yml).

The above API call will retrieve the basic data to display the exam but we have to retrieve the report data via a separate API.

To get the data for the report call `admin/exam-attendance/{examId}` API. 

Also, think of a better way to retrieve the examId from the previous page like a path parameter or another way.

**Comment by Jithmi004** [comment]
https://github.com/cse-mosip/Exam-Attendance-UI/pull/72 This PR should solve this issue
